INSERT INTO Recipes (Id, Name, Ingredients, Instructions, PreparationTime, CookingTime, Servings, Difficulty, Tried, Vegetarian)
VALUES
  ('86e92df5-ec26-4f5d-a9e2-e83e048617bf', 'Spaghetti Bolognese', ARRAY['Spaghetti', 'Ground Beef', 'Tomato Sauce'], 'Boil spaghetti. Brown ground beef. Mix with tomato sauce. Serve over spaghetti.', 15, 30, 4, 'medium', TRUE, FALSE),
  ('d7c9aae5-95cd-4e07-8e32-0a94a73223a1', 'Vegetarian Pizza', ARRAY['Pizza Dough', 'Tomato Sauce', 'Mushrooms', 'Bell Peppers'], 'Roll out pizza dough. Spread tomato sauce. Add mushrooms and bell peppers. Bake until crust is golden.', 20, 25, 6, 'easy', FALSE, TRUE),
  ('16b58e2b-9d65-4c1d-9e3c-ff0cbbe536ec', 'Chicken Alfredo', ARRAY['Fettuccine', 'Chicken Breast', 'Alfredo Sauce'], 'Cook fettuccine. Sauté chicken breast. Mix with Alfredo sauce. Combine with pasta.', 25, 20, 5, 'hard', FALSE, FALSE),
  ('ce2f2851-9d5a-42b1-9445-05ee3a24df4d', 'Caprese Salad', ARRAY['Tomatoes', 'Fresh Mozzarella', 'Basil', 'Balsamic Vinegar'], 'Slice tomatoes and mozzarella. Arrange on a plate. Sprinkle with basil. Drizzle balsamic vinegar.', 10, 0, 2, 'easy', TRUE, TRUE),
  ('1bf7c5ec-2c4f-4c81-9161-741e8e7b5c07', 'Beef Stir-Fry', ARRAY['Beef Strips', 'Broccoli', 'Soy Sauce', 'Ginger'], 'Stir-fry beef strips. Add broccoli, soy sauce, and ginger. Cook until beef is browned and broccoli is tender.', 15, 15, 4, 'medium', TRUE, FALSE),
  ('29b9f267-4cd1-4a95-b2ae-3b066dded586', 'Quinoa Salad', ARRAY['Quinoa', 'Cucumbers', 'Cherry Tomatoes', 'Feta Cheese'], 'Cook quinoa. Mix with diced cucumbers, halved cherry tomatoes, and crumbled feta cheese.', 20, 0, 6, 'easy', FALSE, TRUE),
  ('1739bf02-70cd-4c1f-88c8-bf9ed3ac65d5', 'Shrimp Scampi', ARRAY['Shrimp', 'Linguine', 'Garlic', 'White Wine'], 'Sauté shrimp and garlic in white wine. Cook linguine. Combine shrimp mixture with linguine.', 20, 25, 4, 'hard', FALSE, FALSE),
  ('62f61cda-2c6c-4c3a-8c9d-3d01f0c8ee22', 'Black Bean Tacos', ARRAY['Black Beans', 'Tortillas', 'Salsa', 'Avocado'], 'Heat black beans. Fill tortillas with beans, salsa, and sliced avocado.', 15, 0, 3, 'medium', TRUE, TRUE),
  ('af5ef2d4-50e7-4a4d-9d8b-5d662e0e2e0b', 'Egg Fried Rice', ARRAY['Rice', 'Eggs', 'Peas', 'Carrots'], 'Cook rice. Scramble eggs. Mix rice with scrambled eggs, peas, and diced carrots.', 25, 10, 4, 'easy', TRUE, FALSE),
  ('4e33a3bd-f9c9-41d5-a2e3-0748651500f0', 'Chocolate Cake', ARRAY['Flour', 'Sugar', 'Cocoa Powder', 'Eggs'], 'Mix flour, sugar, and cocoa powder. Add eggs. Bake until a toothpick comes out clean.', 30, 35, 8, 'hard', FALSE, TRUE);